# Generated by Django 5.1.3 on 2026-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalbusiness',
            name='business_id',
        ),
        migrations.AlterField(
            model_name='globalbusiness',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
