# Generated by Django 5.1.3 on 2026-02-23 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_savedbusiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedbusiness',
            unique_together={('user', 'business')},
        ),
    ]
