# Generated by Django 5.1.3 on 2026-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_savedbusiness_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalbusiness',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalbusiness',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalbusiness',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalbusiness',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
